# Makefile for compiling required oct files

all:
	$(MKOCTFILE)       readObj.cc
	$(MKOCTFILE)       writeObj.cc
	$(MKOCTFILE)       longbone_maxDistance.cc
	$(MKOCTFILE)       longbone_Registration.cc
	$(MKOCTFILE)       meshArea.cc
	$(MKOCTFILE)       meshBarycenter.cc
	$(MKOCTFILE)       meshRotation.cc
	$(MKOCTFILE)       meshSection.cc
